name: Compile Solidity Contracts

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: npx hardhat compile
      - name: Check artifact
        run: test -f artifacts/contracts/constructor.sol/LearningContract.json
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: contract-artifact
          path: artifacts/contracts/constructor.sol/LearningContract.json
